### ISSUE TITLE
Disabled products appear in autocomplete

### ISSUE THREAD

**Issue by nmazuz** [Smile-SA/smile-magento-elasticsearch#102]
I disabled some products in my store.
For some reason, the disabled products still appear in autocomplete search result.
I performed reindex but it still there.

Please help!
Niso

**Comment by romainruaud** [comment]
Hello,

this may be due to the autocomplete cache not being expired properly.

How did you disabled these products ? If this is done via an import process or anything else than manually saving them in the back-office, the cache purge may have not been triggered properly.

regards

**Comment by romainruaud** [comment]
I close this one for being inactive way too long.

Do not hesitate to reopen it if you're still facing issues.

Best regards
