### ISSUE TITLE
Bestseller option in product listing

### ISSUE THREAD

**Issue by alinalexandru** [Smile-SA/smile-magento-elasticsearch#104]
Is there an option to sort products by bestselling?

**Comment by romainruaud** [comment]
Hello @alinalexandru 

You can configure a boost based on top sales by following the documentation of the latest 1.4 release here : 

https://github.com/Smile-SA/smile-magento-elasticsearch/blob/release_1.4/doc/behavorial-search.md

But for now you will not be able to add "Top Sales" as an available sort order for users in frontend.

Regards,
