### ISSUE TITLE
Sorting based on Newest And Oldest by Set Product as New From using elastic 

### ISSUE THREAD

**Issue by mukdam** [Smile-SA/smile-magento-elasticsearch#110]
I want to shorting based  Set Product as New From and To Date on Catalog listing.

![image](https://cloud.githubusercontent.com/assets/10529768/25888058/3ff44432-3582-11e7-96da-b7769bde14c0.png)

**Comment by romainruaud** [comment]
@mukdam you are showing a Magento2 screenshot.

The dedicated github for the Magento2 module is here : https://github.com/Smile-SA/elasticsuite/

Regards,
