### ISSUE TITLE
Paid support

### ISSUE THREAD

**Issue by sylvainraye** [Smile-SA/smile-magento-elasticsearch#113]
Hi, 

Any possibilities to have support against payment for faster and high priority support ?

Main reason, we have a 6 until 7 hours time of reindexing for around 15000 Documents into ES including two store views. We would like to make it faster. Using more replicas didn't helped a lot and even broke some times to times

Thank you for your reply

**Comment by djenvert** [comment]
Hello,
Strange and unusual indexing times. We'll contact you directly by email early next week.

**Comment by romainruaud** [comment]
We did contact you by email, so I close this one for now,

Best regards,
