### ISSUE TITLE
Fatal error: Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in D:\xampp\htdocs\folder\app\code\community\Smile\ElasticSearch\Model\Indexer\Fulltext.php on line 181

### ISSUE THREAD

**Issue by hkvega01** [Smile-SA/smile-magento-elasticsearch#114]
i'm trying to build a magento testing site in local windows (xampp, php5.6.x) , i installed elasticsearch 5.5 on windows and the following is output of http://localhost:9200/ 

```
{
  "name" : "DESKTOP-QE1Q206",   //this is the computer name
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ssvHstK_SHyfQuX2YwxCSw",
  "version" : {
    "number" : "5.5.0",
    "build_hash" : "260387d",
    "build_date" : "2017-06-30T23:16:05.735Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
```
in magento setting, the "alias name" was set to "elasticsearch", but when i reindex 

"Catalog Search Index | Rebuild Catalog product fulltext search index"

manually in backend, it produces the following error

Fatal error: Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in D:\xampp\htdocs\folder\app\code\community\Smile\ElasticSearch\Model\Indexer\Fulltext.php on line 181

Anyone know how to fix the problem?

**Comment by kirmorozov** [comment]
Just Reindex.

**Comment by romainruaud** [comment]
Hello @hkvega01 

Elasticsuite is not defined as the search engine in the configuration.

Please select it via Catalog > Catalog Search > Search Engine.

But, we do not support ES 5.5 for the Magento 1 version.

We support only **ES 1.x** : please use Elasticsearch **1.7**

You also have to install two required modules : analysis-phonetic and analysis-icu

Best regards, I close the issue for now, do not hesitate to reopen it if needed.
