### ISSUE TITLE
Store/Website level attribute filtering issue on virtual category

### ISSUE THREAD

**Issue by vo1** [Smile-SA/smile-magento-elasticsearch#116]
Issue on filtering virtual category on store/website scope attributes when no global fallback value present in database.

Steps to reproduce:

1. Create an attribute lets make it very simple Boolean and name it vcat with store/website scope, assign it to attribute set.
2. Find existing product with attribute set containing vcat, select store/website scope and change attribute vcat to be yes.
3. Go to categories and select store view of product that was updated above.
4. Create virtual category filter for this attribute, when vcat = yes, you will see no products in the list. Reindexing won't help.

To make product appear - go to product, select "All store views" and simply click save. The global value (regardless of its yes or no) will be pushed to DB and ES and product will appear. I remember a bug like that in M1, when no global-value was present in db for the entity, some of sql queries were not able to get store-specific value.

**Comment by romainruaud** [comment]
Imho this is a Magento bug. Products should not have null value for global scope.

Which version of Magento are you using ?

**Comment by vo1** [comment]
2.1.7

**Comment by romainruaud** [comment]
My bad, then please open the issue on the proper repository for the M2 module, here : https://github.com/Smile-SA/elasticsuite/
