### ISSUE TITLE
SearchPhaseExecutionException[Failed to execute phase [query_fetch]

### ISSUE THREAD

**Issue by samc-2810** [Smile-SA/smile-magento-elasticsearch#12]
Hi,
I get the above error on Category-Page and search-result. However, auto complete seems to be working. I am using magento 1.9 and was using the BubbleSearch-Extension for ES (which works)
I have already deactivated VirtualCategories Module

Could you help me get the Extension working as this really looks like a great extension and thanks for that

**Comment by nicosomb** [comment]
Hello @samc-2810!

What is your ES version? 
Did you try to upgrade ES? 
Can you reinstall the module? Can you try to reindex all, to clear cache?
