### ISSUE TITLE
Filter Layered Navigation is not display actual result.

### ISSUE THREAD

**Issue by magentounit2** [Smile-SA/smile-magento-elasticsearch#142]
I have set custom conditions for my requirement and I have created plugin from **\Magento\Catalog\Model\Layer** with `public function afterGetProductCollection(\Magento\Catalog\Model\Layer $subject,$result)
    {
    $getProductUniqueIds = array(1,2,3,4,5);
    $result->addAttributeToFilter('entity_id',array('in' => $getProductUniqueIds)); return $result; }`

Using above conditions, I have display Product collection properly but Layered navigation is not display based on above conditions. Its display old layered navigation without considering filter conditions.

![layer-navigation](https://user-images.githubusercontent.com/28340827/41760155-a9299c3a-760f-11e8-9e20-42ed71eac5a7.png)

Would I need to set above product collection conditions to other files also? or What's the problem with my custom conditions in layer.php with plugins?

Any help regarding above criteria @romainruaud 

Thanks.

**Comment by romainruaud** [comment]
Hello @magentounit2 

This repository concerns the Magento1 version of our module.

Please move your question to the magento2 repository here : https://github.com/Smile-SA/elasticsuite/

Regards
