### ISSUE TITLE
Weird error when trying to configure redis

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/smile-magento-elasticsearch#143]
I tried your module and I had some minor issues so I decided to not use it for this project.

So I uploaded the project to production server and put it in prod mode. All smile modules are set to 0 in config.php.

Now I tried to configure redis: 
`php bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-db=4`

Then I got this seemingly unrelated error: 
> Unable to connect ElasticSearch server : No alive nodes found in your cluster

Could there be any remainders of your module interfering with the redis config?

**Comment by romainruaud** [comment]
Hello @OvalMedia 

This repository concerns the Magento1 version of our module.

Please move your question to the magento2 repository here : https://github.com/Smile-SA/elasticsuite/

Regards
