### ISSUE TITLE
Error creating elastic search index

### ISSUE THREAD

**Issue by sandeep-mukherjee** [Smile-SA/smile-magento-elasticsearch#144]
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0. You should now use either a [text] or [keyword] field instead for field [sku]"}],"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0. You should now use either a [text] or [keyword] field instead for field [sku]"},"status":400}

I am using elastic suite 2.5.0 and elastic search 5.0 Magento EE 2.3

**Comment by romainruaud** [comment]
Hello @sandymu123 

This repository concerns the Magento1 version of our module.

Please move your question to the magento2 repository here : https://github.com/Smile-SA/elasticsuite/

Regards
