### ISSUE TITLE
Cannot reindex data to elastic search server

### ISSUE THREAD

**Issue by darshan-khatri-16** [Smile-SA/smile-magento-elasticsearch#145]
I am facing below error when I reindex data from magento to elastic search server.

Please let me know what should I do? I am working on elastic search version 2.4. Magento enterprise edition.

[atos@911617-stage httpdocs]$ php shell/indexer.php --reindexall
Stock Status index was rebuilt successfully in 00:00:00
Catalog product price index was rebuilt successfully in 00:00:00
Category URL Rewrites index was rebuilt successfully in 00:00:00
Product URL Rewrites index was rebuilt successfully in 00:00:00
URL Redirects index was rebuilt successfully in 00:00:00
Catalog Category/Product Index index was rebuilt successfully in 00:00:00
Catalog Search Index index process unknown error:
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://192.168.100.173:9200/elasticsearch-20180717-054642' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#17 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/elasticsearch-...', Array, '{"settings":{"n...')
#18 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/elasticsearch-...', Array, Array)
#19 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(368): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#21 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(449): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#22 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#23 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#24 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#25 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#26 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()
#27 {main}

Next exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"illegal_argument_exception","reason":"Unknown TokenFilter type [phonetic] for [beidermorse_en]"},"status":400}' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:266
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"settings":{"n...')
#1 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/elasticsearch-...', Array, '{"settings":{"n...')
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/elasticsearch-...', Array, Array)
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(368): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(449): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#7 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#8 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#9 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#10 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#11 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()
#12 {main}
Search Terms products positions Indexer index process unknown error:
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 404
[reason phrase] Not Found
[url] http://192.168.100.173:9200/elasticsearch-20180717-054642/product/_search?size=1000&scroll=5m&search_type=scan' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"term...')
#17 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/elasticsearch-...', Array, '{"query":{"term...')
#18 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/elasticsearch-...', Array, Array)
#19 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(109): Elasticsearch\Client->search(Array)
#21 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(62): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->_updateStoreEntities('1')
#22 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(59): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData('1', NULL)
#23 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Indexer/Search/Terms/Position.php(123): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData()
#24 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Search_Terms_Position->reindexAll()
#25 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#26 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#27 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()
#28 {main}

Next exception 'Elasticsearch\Common\Exceptions\Missing404Exception' with message '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch-20180717-054642","index":"elasticsearch-20180717-054642"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch-20180717-054642","index":"elasticsearch-20180717-054642"},"status":404}' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:260
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"query":{"term...')
#1 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"term...')
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/elasticsearch-...', Array, '{"query":{"term...')
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/elasticsearch-...', Array, Array)
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(109): Elasticsearch\Client->search(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(62): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->_updateStoreEntities('1')
#7 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(59): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData('1', NULL)
#8 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Indexer/Search/Terms/Position.php(123): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData()
#9 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Search_Terms_Position->reindexAll()
#10 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#11 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#12 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()
#13 {main}
Custom products positions in Virtual Categories index process unknown error:
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 404
[reason phrase] Not Found
[url] http://192.168.100.173:9200/elasticsearch-20180717-054642/product/_search?size=1000&scroll=5m&search_type=scan' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"term...')
#17 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/elasticsearch-...', Array, '{"query":{"term...')
#18 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/elasticsearch-...', Array, Array)
#19 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(109): Elasticsearch\Client->search(Array)
#21 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(62): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->_updateStoreEntities('1')
#22 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(59): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData('1', NULL)
#23 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/VirtualCategories/Model/Indexer/VirtualCategories/Product/Position.php(132): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData()
#24 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_VirtualCategories_Model_Indexer_VirtualCategories_Product_Position->reindexAll()
#25 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#26 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#27 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()
#28 {main}

Next exception 'Elasticsearch\Common\Exceptions\Missing404Exception' with message '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch-20180717-054642","index":"elasticsearch-20180717-054642"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch-20180717-054642","index":"elasticsearch-20180717-054642"},"status":404}' in /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:260
Stack trace:
#0 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"query":{"term...')
#1 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"term...')
#2 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/elasticsearch-...', Array, '{"query":{"term...')
#3 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/elasticsearch-...', Array, Array)
#4 /var/www/vhosts/stage.exair.com/httpdocs/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(109): Elasticsearch\Client->search(Array)
#6 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(62): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->_updateStoreEntities('1')
#7 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Mapping/DataProvider/Abstract.php(59): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData('1', NULL)
#8 /var/www/vhosts/stage.exair.com/httpdocs/app/code/community/Smile/VirtualCategories/Model/Indexer/VirtualCategories/Product/Position.php(132): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_DataProvider_Abstract->updateAllData()
#9 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(212): Smile_VirtualCategories_Model_Indexer_VirtualCategories_Product_Position->reindexAll()
#10 /var/www/vhosts/stage.exair.com/httpdocs/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#11 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#12 /var/www/vhosts/stage.exair.com/httpdocs/shell/indexer.php(216): Mage_Shell_Compiler->run()

Thanks,
Rushvi Gajjar.

**Comment by romainruaud** [comment]
Hello @darshan-khatri-16 

This repository concerns the Magento1 version of our module.

Please move your question to the magento2 repository here : https://github.com/Smile-SA/elasticsuite/

Regards

**Comment by darshan-khatri-16** [comment]
Hi Romain,

We are currently using Magento version 1.14 enterprise edition. We are not using Magento2. We have raised request for Magento1.

**Comment by darshan-khatri-16** [comment]
Hi Romain,


My question was for Magento version 1 not for Magento version 2.


Thanks & regards,
Darshan Khatri | Sr. Software Engineer | e-Zest Solutions Ltd. | IT -9 Bldg 3rd Floor, NTPL-SEZ Hinjewadi Phase-1, Pune- 411 057 | Cell: +91 80004 90855 | darshan.khatri@e-zest.in<mailto:anjali.kondhare@e-zest.in> | http://www.e-zest.com/

Email Disclaimer<http://e-zest.net/emaildisclaimer.html>


________________________________
