### ISSUE TITLE
ElasticSearch not Working

### ISSUE THREAD

**Issue by kayaj** [Smile-SA/smile-magento-elasticsearch#17]
Hey Guys!
First my Setup... Server: nginx // PHP: 5.6.2 // Magento CE: 1.9.1.0
I've already worked with Elasticsearch with another Magento Extension, this worked. I can confirm that the elastic search Server works. (v 1.4.5)
![Screenshot](https://cloud.githubusercontent.com/assets/4310449/8702069/b9d36f86-2b15-11e5-9bbf-993d39712081.jpg)
First of all, I'm not able to reindex from the Admin Panel. But Reindexing from shell works. But I don't think this is related to my issue.
The Problem is: I don't get any search-suggestions, nor a Quickresult Popup. When Submitting the Search, it seems as if the results fallback to the Magento SQL Search. 
The Extension seems to work, because after I've uploaded it, the search form slightly changed in design and there appeared a link "extended search" which wasn't there.
I have no idea what I can do to get it working because there's no error. Anything I forgot to do after installing the extension (and configuring).

best
Jakob

**Comment by devromans** [comment]
Hello, I think it's linked to your another issue #18 . ManaDev extension rewrites standard Magento functionality. Which version of ManaDev Layered SEO Filters do you use?

**Comment by kayaj** [comment]
hey devromans, thank you for responding. I'm using the latest version of Layered SEO Filters, but I can't find a Version Number of the Extension... The latest change to some of the files of the extension was 16. June 2015, I guess It's really the latest version.

**Comment by devromans** [comment]
You can check my merge request #20, probably it will help to you. Works for me with Magento 1.9.2.0 and ManaDev Layered SEO filters v. 14.01.05.18

P.S. which version of PHP installed on your server?

**Comment by kayaj** [comment]
Hi Devromans
I've uploaded the changes, sadly I'm still having issues, when I'm trying to navigate to a subcategory that contains Manadev SEO filters. - **The search / autocomplete works now as expected in the frontend**
I guess something still has issues with the manadev virtual filter-categories...

So, what still doesn't work: 
1. Magento Backend Reindexing (I'm reindexing via the shell reindexer)
2. Category-Listings that contain MANAdev SEO Filters receive following error:
> Warning: explode() expects parameter 2 to be string, array given  in [webroot]/app/code/local/Mana/Seo/Rewrite/Url.php on line 419
> 
> #0 [internal function]: mageCoreErrorHandler(2, 'explode() expec...', '/var/www/client...', 419, Array)
> #1 [webroot]/app/code/local/Mana/Seo/Rewrite/Url.php(419): explode('_', Array)
> #2 [webroot]/app/code/local/Mana/Seo/Rewrite/Url.php(137): Mana_Seo_Rewrite_Url->_generateAttributeParameter(Object(Mana_Seo_Model_Url), Array)
> #3 [webroot]/app/code/core/Mage/Core/Model/Url.php(763): Mana_Seo_Rewrite_Url->getRoutePath(Array)
> #4 [webroot]/app/code/core/Mage/Core/Model/Url.php(995): Mage_Core_Model_Url->getRouteUrl('*/*/*', Array)
> #5 [webroot]/app/code/local/Mana/Seo/Rewrite/Url.php(83): Mage_Core_Model_Url->getUrl('*/*/*', Array)
> #6 [webroot]/app/Mage.php(394): Mana_Seo_Rewrite_Url->getUrl('*/*/*', Array)
> #7 [webroot]/app/code/core/Mage/Catalog/Model/Layer/Filter/Item.php(63): Mage::getUrl('*/*/*', Array)
> #8 [webroot]/app/code/local/Amasty/Xlanding/Model/Catalog/Layer/Filter/Item.php(16): Mage_Catalog_Model_Layer_Filter_Item->getUrl()
> #9 [webroot]/app/design/frontend/base/default/template/smile/elasticsearch/catalog/layer/filter.phtml(19): Amasty_Xlanding_Model_Catalog_Layer_Filter_Item->getUrl()
> #10 [webroot]/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/client...')
> #11 [webroot]/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
> #12 [webroot]/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
> #13 [webroot]/app/code/core/Mage/Catalog/Block/Layer/Filter/Abstract.php(154): Mage_Core_Block_Template->_toHtml()
> #14 [webroot]/app/design/frontend/smartwave/granada/template/catalog/layer/view.phtml(46): Mage_Catalog_Block_Layer_Filter_Abstract->getHtml()
> #15 [webroot]/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/client...')
> #16 [webroot]/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/smartw...')
> #17 [webroot]/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
> #18 [webroot]/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
> #19 [webroot]/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
> #20 [webroot]/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
> #21 [webroot]/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
> #22 [webroot]/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('left', true)
> #23 [webroot]/app/design/frontend/smartwave/granada/template/page/2columns-left.phtml(59): Mage_Core_Block_Abstract->getChildHtml('left')
> #24 [webroot]/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/client...')
> #25 [webroot]/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/smartw...')
> #26 [webroot]/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
> #27 [webroot]/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
> #28 [webroot]/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
> #29 [webroot]/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
> #30 [webroot]/app/code/core/Mage/Catalog/controllers/CategoryController.php(161): Mage_Core_Controller_Varien_Action->renderLayout()
> #31 [webroot]/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_CategoryController->viewAction()
> #32 [webroot]/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
> #33 [webroot]/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
> #34 [webroot]/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
> #35 [webroot]/app/Mage.php(684): Mage_Core_Model_App->run(Array)
> #36 [webroot]/index.php(87): Mage::run('de', 'store')
> #37 {main}

The PHP version I use is:5.6.2 (as mentioned in the first post) :smiley: 

Thank you for your help so far!

**Comment by afoucret** [comment]
This bug is not related to our module but rather to the manadev extension. You should ask them to make it compatible with our module and handle the case where there is multiple filters applied into their URL rewrite.

I close this issue.
