### ISSUE TITLE
Fatal error: Call to undefined method Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch::isLeyeredNavigationAllowed() 

### ISSUE THREAD

**Issue by kayaj** [Smile-SA/smile-magento-elasticsearch#18]
In the left sidebar, where ManaDev Layered SEO Filters usually appear this error occured after installing the Magento extension.
> Fatal error: Call to undefined method Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch::isLeyeredNavigationAllowed() in [...]/app/code/local/Mana/Filters/Block/View.php on line 179

Anyone an idea what causes this error?

**Comment by kayaj** [comment]
I sense a typo...  isL**e**yered
probably this?

**Comment by kayaj** [comment]
Fixed the Typo -> Error-message disappeared.
**BUT**
On a different Magento installation I'm using the same extension, and there I had to leave the typo in the code. When I corrected the typo there, I've received an error message. **WITH** typo it works like a charm. **WITHOUT** I get an error. I think it depends on your setup...

**Comment by nicosomb** [comment]
Hello @kayaj ,

> I've received an error message.

The same than in your 1st post?

**Comment by afoucret** [comment]
There is no way our module can work with this : http://www.manadev.com/advanced-layered-navigation-ce/ (I suspect you are talking about this module) 

I don't want enter into technical details but we are providing the same facet multiselect mode and it comes the time were we override the same code (and they get incompatible).

Our module does a lot more actually even if we speak only about facets (price sliders, rating filters, ...) !!!

So you have to uninstall your module if you want to enjoy our !!!

**Comment by Tomasz-Silpion** [comment]
Exaggerated. At least basic compatibility can be simply added. I've managed to made it work on my store in circa 2h.

https://github.com/Smile-SA/smile-magento-elasticsearch/pull/151
