### ISSUE TITLE
If category not include any product error

### ISSUE THREAD

**Issue by ksaltik** [Smile-SA/smile-magento-elasticsearch#2]
Fatal error: Call to a member function getSearchQuery() on a non-object in C:\xampp\htdocs\oneyhosting.com\app\code\community\Smile\VirtualCategories\Model\Observer.php on line 57

When a category ; that not include any product; clicked from frontend we get above error.

**Comment by afoucret** [comment]
Did you check the settings as asked in my response to issue #1 ?

**Comment by afoucret** [comment]
@ksaltik,

Any news about this issue ?

**Comment by afoucret** [comment]
Without Without response from you we can not go further on this.
So, I close the issue.
