### ISSUE TITLE
Method called on non-object

### ISSUE THREAD

**Issue by brucemead** [Smile-SA/smile-magento-elasticsearch#24]
( ! ) Fatal error: Call to a member function addFilter() on a non-object in app/code/community/Smile/VirtualCategories/Model/Resource/Catalog/VirtualCategory/Collection.php on line 90

Solution is to change the method to: 
`
    public function getQuery()
    {
        $query = false;
        $engine = Mage::helper('catalogsearch')->getEngine();

        if ($engine instanceof Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch) {
            $query = $engine->createQuery('product');
            $query->addFilter('terms', array('store_id' => $this->getProductStoreId()));
        }

        return $query;
    }
`

**Comment by nicosomb** [comment]
Hello @brucemead !

I agree with your fix, but can you tell me when you obtain this error please?

**Comment by afoucret** [comment]
This change has been applied at commit 0f5eea5ee90d9134ca359321c9722dc4b68e8402.
I close the issue then.
