### ISSUE TITLE
Unable to use decimal aatribute

### ISSUE THREAD

**Issue by roshnibharambe** [Smile-SA/smile-magento-elasticsearch#27]
We have some attributes which haves decimal values. I have installed this module and it works fine for all values except decimal. 

It gives me the following error.

Call to undefined method Smile_ElasticSearch_Helper_Data::getAttributeFieldName() in app/code/community/Smile/ElasticSearch/Model/Catalog/Layer/Filter/Decimal.php on line 136.

Is it possible to have decimal  attribute values with this module?

**Comment by nicosomb** [comment]
Hello @roshnibharambe, 

When you talk about decimal, what do you mean? Can you give me an example please? 
I tried with "2,5" and "2.5", it works fine.

**Comment by roshnibharambe** [comment]
Hello @nicosomb ,

decimal means 1.2 , 0.01.

**Comment by nicosomb** [comment]
OK, so it seems to be like my tests. Did you launch a reindex after your changes?

**Comment by roshnibharambe** [comment]
Yes. i have re-indexed all data twice.

On Fri, Aug 28, 2015 at 2:40 PM, Nicolas Lœuillet <notifications@github.com>
wrote:

> OK, so it seems to be like my tests. Did you launch a reindex after your
> changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smile-SA/smile-magento-elasticsearch/issues/27#issuecomment-135700338>
> .
>



-- 
Thanks & Regards,
Roshani Bharambe
+91 8879431195
Ambab Infotech Pvt Ltd.
http://www.ambab.com

**Comment by afoucret** [comment]
The bug is well known.
If you want to fix it you have to disable faceting on this attribute. Then everything should be ok again.

I have to backport the patch a colleague of me has done for a project in order to be able to use it has a filter.

**Comment by afoucret** [comment]
The patch will be available very soon. I need to clean one or twio things before it will be merged.

FYI, Decimal and integer attributes facets will be rendered just like price range filter as you can see in the following example :

<img width="212" alt="capture d ecran 2015-09-22 a 17 26 15" src="https://cloud.githubusercontent.com/assets/529238/10022816/12d15f16-614f-11e5-812d-bd6f1a208248.png">

**Comment by afoucret** [comment]
This have been fixed since 79d980eb.

If you are using ES > 1.7 (officially not supported), be careful that you should add this to your elasticsearch.yml config file : 
```
script.inline: on
script.indexed: on
```
