### ISSUE TITLE
Not able to select  more than 2 values for same attribute

### ISSUE THREAD

**Issue by roshnibharambe** [Smile-SA/smile-magento-elasticsearch#28]
I have installed this module and it gives me error when i select two values for same attribute.

example: if i select one color say yellow. then it works perfect but i select two colors say yellow and blue it will gives me "No result found" while there are some products having blue color.

**Comment by nicosomb** [comment]
Hello @roshnibharambe,

Can you try to reindex you data please? I just tried to select two values for the same attribute (for example, two colors with magento sample data) and it works fine, I've got 2 products, one per color.

**Comment by afoucret** [comment]
We just pushed a lot of code today.
Can you please try to reindex and say us if the issue is still there ?

**Comment by afoucret** [comment]
Any status on this ?
Should I close the issue ?

**Comment by roshnibharambe** [comment]
yes, you can close this issue. Its working proper.

On Mon, Oct 5, 2015 at 11:19 PM, Aurélien FOUCRET <notifications@github.com>
wrote:

> Any status on this ?
> Should I close the issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smile-SA/smile-magento-elasticsearch/issues/28#issuecomment-145611634>
> .
>



-- 
Thanks & Regards,
Roshani Bharambe
+91 8879431195
Ambab Infotech Pvt Ltd.
http://www.ambab.com

**Comment by afoucret** [comment]
Great an thx for your feedback
