### ISSUE TITLE
Error creating elastic search index after installing module

### ISSUE THREAD

**Issue by ali-husain** [Smile-SA/smile-magento-elasticsearch#30]
Hello,  I installed this module on Magento 1.9.2.1 using Elasticsearch version 1.7.1 but I immediately get the following exception when performing a reindexall.  

Catalog Search Index index process unknown error:
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://127.0.0.1:9200/sac-20150918-220533' in /var/www/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /var/www/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /var/www/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#17 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/sac-20150918-2...', Array, '{"settings":{"n...')
#18 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/sac-20150918-2...', Array, Array)
#19 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /var/www/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(369): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#21 /var/www/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(450): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#22 /var/www/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#23 /var/www/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#24 /var/www/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#25 /var/www/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#26 /var/www/shell/indexer.php(216): Mage_Shell_Compiler->run()
#27 {main}

Next exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"IndexCreationException[[sac-20150918-220533] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find token filter type [phonetic] for [beidermorse_en]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [phonetic]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.phonetic.PhoneticTokenFilterFactory]; ","status":400}' in /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:266
Stack trace:
#0 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"settings":{"n...')
#1 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#2 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/sac-20150918-2...', Array, '{"settings":{"n...')
#3 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/sac-20150918-2...', Array, Array)
#4 /var/www/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(369): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#6 /var/www/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(450): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#7 /var/www/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#8 /var/www/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#9 /var/www/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#10 /var/www/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#11 /var/www/shell/indexer.php(216): Mage_Shell_Compiler->run()
#12 {main}

**Comment by afoucret** [comment]
Look like the phonetic analyzer plugin of ElasticSearch is missing in your install
Did you run the install script ?

The requirement are now :
- ES 1.5
- elasticsearch/elasticsearch-analysis-phonetic/2.5.0 plugin (https://github.com/elastic/elasticsearch-analysis-phonetic)

Can you try to install the plugin and reindex the fulltext search ?

**Comment by ali-husain** [comment]
Note that I had installed all of the necessary extensions with ES 1.7 previously.

But I uninstalled elastic search taking care to remove the directories as well (as ES doesn't uninstall cleanly).  I then installed using the install-es.sh script and am having the same problem with ES 1.5

I'm running on Ubuntu 14.04 and the installed plugins are as follows;

Installed plugins:
    - head
    - analysis-icu
    - analysis-phonetic
    - kopf


I noticed the tracking indexer is the only thing that fails in the install script is the tracking-indexer which is not present in your repo.  "$ES_PLUGIN_CMD -install tracking-indexer -u file:$ES_LOCAL_PLUGIN_DIR/tracking-indexer/tracking-indexer-current.jar"

**Comment by Swahjak** [comment]
I have been having the same problem as @ali-husain. My store language is dutch so I think something is going wrong with switching between "beiderMorseLanguages" and "snowballLanguages". When I manually change (Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_Catalog_Eav_Abstract line 77):
```
$mapping['properties']['spelling_' . $languageCode]['fields']['phonetic_' . $languageCode] = array(
                'type' => 'string', 'analyzer' => 'phonetic_' . $languageCode, 'store' => false
            );
```
To
```
$mapping['properties']['spelling_' . $languageCode]['fields']['snowbal_' . $languageCode] = array(
                'type' => 'string', 'analyzer' => 'analyzer_' . $languageCode, 'store' => false
            );
```

The index will run. The is no check on whether it should use a snowball language vs a beider morse language.

Not sure if this is the actual problem, haven't been through all the code, but it does temporarily solve the problem for me.

**Comment by Swahjak** [comment]
As an addition, this seems more valid (if it's the solution at all) since it is also used in Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Mapping_Catalog_Eav_Abstract::_getStringMapping

```
if ($this->getCurrentIndex()->isPhoneticSupported($languageCode)) {

                $mapping['properties']['spelling_' . $languageCode]['fields']['phonetic_' . $languageCode] = array(
                    'type' => 'string', 'analyzer' => 'phonetic_' . $languageCode, 'store' => false
                );
            }
```

**Comment by ali-husain** [comment]
I switched to another ES extension for now, but I'll try what you've suggested and look into the issue further as well.  Thanks @Swahjak for your input.

**Comment by johandekruijf** [comment]
I ran into a similar problem as Swahjak, my store language is also dutch.
I found out that dutch is not a Beider-Morse algorithm supported language.
After I added 'dutch' to the list of supported languages (in app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php) I could re-index without errors.

**Comment by Swahjak** [comment]
@afoucret @johandekruijf Can confirm that this also seems to fix the issue for me (with a dutch store). Not sure though if it's a valid one. The only reference I can find between the 'beider morse algorithm' and 'dutch' seems to be http://stevemorse.org/phonetics/bmpm2.htm. It does state the following;

>The languages we currently support are Catalan, Czech, Dutch, English, French, German, Greek (in Greek characters as well as translitered into Latin characters), Hebrew, Hungarian, Italian, Polish, Portuguese, Romanian, Russian (in Cyrillic characters as well as various transliterations), Spanish (including its Latin American dialects), and Turkish.  New language tables will probably be added in the future.

But I can't seem to find any relevant information about the support in Elasticsearch or the Phonetic plugin. (Also notice the linked page is phonetics/bmpm<b>2</b>.htm, http://stevemorse.org/phonetics/bmpm.htm is also a valid page).

**Comment by afoucret** [comment]
The last version of the code pushed this morning fix both point : 

* Remove the local smile plugin reference into install (it should never have been pushed here)
* No error when using a not supported language

Warning for people using ES  >= 1.7 even if not officially supported. You have to addthe following lines into your elasticsearch.yml configuration file : 

```
script.inline: on
script.indexed: on
```

instead of : 

```
script.disable_dynamic: false
```

This is due to the new script handling of ES.
