### ISSUE TITLE
Attribute having multiple select input type is now coming in filters

### ISSUE THREAD

**Issue by roshnibharambe** [Smile-SA/smile-magento-elasticsearch#33]
I had integrated this plugin successfully and i can see all my attributes in filters except "color" attribute. This attribute has multiple select input type.

Please help me.

**Comment by afoucret** [comment]
This issue was fixed by 77645af.

You should be able to see facets on multiselect attributes after you have reindexed catalog search (the bug was mostly due to attributes created from the admin since they don't have default source_model in this case).

BR,
