### ISSUE TITLE
Price slider not available when doing a quick-search only available when selecting a category.html first

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/smile-magento-elasticsearch#34]
When I search using a quick search "ABC PRODUCT" if I do not use auto-complete but press enter and the results are missing the pricing slider!

If i select an autocomplete drop-down category -> the pricing slider is present!

Also when many manufacturers are present, sometimes there is a javascript search box to sub-search the manufacturers to select? Only sometimes!

Lastly - how hard would it be to add ability to nest textual search and add the search to the breadcrumb search? (not a bug)

Using Firefox current with ublock on windows 7!

**Comment by afoucret** [comment]
1) About the missing price slider
Can you post : 
* the URL
* the screenshot of page where the slider is missing

Are tou sure price is enabled as a facet in search and not only in category navigation ?
Please check that both "Use In Search Results Layered Navigation" is set to "Yes" into Catalog -> Attributes -> Color from the admin.

2) About the internal facet search engine : 

It just work as expected by me.
It appears when the number of values into the facet is to important to be displayed.
You will also notice there is a small "Show more" link into the right bottom corner of the facet.
You can set the max number of item displayed before the box appears attribute by attribute.
Here is my configuration in Catalog -> Attributes -> Color : 

<img width="552" alt="capture d ecran 2015-10-06 a 19 47 50" src="https://cloud.githubusercontent.com/assets/529238/10317225/b3155f12-6c63-11e5-8de6-a860a24fcc48.png">

You can put a larger value here but be careful to not set a value which is too high.
As a user having too much choice is a distraction and you can feel lost.
The perfect value is between 5 and 10 depending the number of facets you will have to display on the same page.
Technically it can slow the search query to require to much value of too much facets. 
But you can put 100 if you find it is a good idea.

3) Fear I don't understand what do you mean by "ability to nest textual search and add the search to the breadcrumb search"

**Comment by afoucret** [comment]
Note: next time can you open one issue by subject. 
It is easier to follow for me.
More important it is easier for user to search on specific issue and response.

By advance, thank you.

**Comment by southerncomputer** [comment]
Thank you I have figured out #1 and #2 by your help! Hard to work out all the excellent features!

#3 means when you search via quick-search, you can further narrow down the search by using nested search terms! Like this web search!
![capture](https://cloud.githubusercontent.com/assets/6178967/10317755/fcbc69ec-6c33-11e5-9ef6-d83afb524bd5.PNG)

**Comment by afoucret** [comment]
>  Hard to work out all the excellent features!
Happy that you enjoy it. To be honest we are moving faster on the features than on the documentation since we are releasing our master only. It will be fixed soon with a better release management.

> For nested search queries it requires custom development (not on my roadmap). I think it is possible but not easy to do. 
You will should start by looking at the smile_elasticsearch_query_assembled observers.
It allows to plug custom logic before the query is sent to ES. So maybe you block can instantiate a array of additional query terms and  the observers append the additional query terms. But as said before it will not be easy since query composition is an hard task (you have to spellcheck, use the good analyzers and so on, ...).

For my part I considered the issue as closed.
