### ISSUE TITLE
on search error

### ISSUE THREAD

**Issue by SiddiqueAhmad** [Smile-SA/smile-magento-elasticsearch#47]
Fatal error: Call to undefined method Mage_Catalog_Model_Resource_Product_Collection::isSpellchecked() in /home/esajee/public_html/esajee.com/app/code/community/Smile/ElasticSearch/Block/Catalogsearch/Result.php on line 31

it was running fine before, not sure what we change in setting of attributes that this error came

**Comment by romainruaud** [comment]
This can happen when ES is not running, this is due to the fact that Magento falls back to it's standard search engine, and then uses its native Collection model which does not have this method.

Are you still facing the issue ?

**Comment by EsajeeSolutions** [comment]
i am glad you replied, no it was solved, only the elastic search was not running

**Comment by romainruaud** [comment]
Fine,

then I close this issue.

Thank you for submitting it.

**Comment by mobilizer** [comment]
I suggested a pull request to solve the error when ES server is down, unavailable or disabled in Magento config: #88 
(I think ES server unavailability should be handled.)

**Comment by kirmorozov** [comment]
ES server unavailability should be handled, by making it available.
There are cases when 70-80 of sales are going through search.
Such fallback will just crash the system(put mysql down due to overload).
There is no point of doing such failover, its like redis, part of system.

**Comment by mobilizer** [comment]
Two points: 
1.) I think it is no good idea to premise the availability of the search server for the functionality of the complete system. (E.g. See the massive DDOS attack last week.)
2.) Current implementation has no fallback handling. And the error is unhandled and can be avoided relatively simple. (Yes.. for high volume sites, search should be just disabled if ES server is away... But current implementation already does a fallback to default Magento catalogsearch, but fails on block output. So the workload is already there.)

**Comment by kirmorozov** [comment]
1.) Just scale your cluster, make it unbreakable. Depends on reason of failure. Make your system successful to attract DDoS
2.) Looks like you want to index data twice or have out-dated index.

**Comment by mobilizer** [comment]
@kirmorozov Have you looked at the source lines generating the error? Better keeping a case with an unhandled "undefined methode" error? Really?

**Comment by ZaneCEO** [comment]
Hi guys,
I need to switch back to Magento MySQL search due to project needs. We will probably go back to ES in the future, but, still, for now I need Magento basic search.

I tired to select `MySQL` from `Search Engine`, but I get this exact  error on `isSpellchecked()`. Can we do something about it?

**Comment by riconeitzel** [comment]
@ZaneCEO https://github.com/Smile-SA/smile-magento-elasticsearch/pull/88 implement this fix!

**Comment by ZaneCEO** [comment]
@riconeitzel Thanks for your reply! Yet, #88 is not merged yet, I'm I wrong? If so: which tag/release has it?

**Comment by riconeitzel** [comment]
No Tag  … also this repo looks like there's no active maintainer … just take the code and put that into your system!

Rico

**Comment by ZaneCEO** [comment]
Thanks Rico, I will!
