### ISSUE TITLE
Can't update non dynamic settings[[index.merge.policy.merge_factor]] for open indices

### ISSUE THREAD

**Issue by grizwako** [Smile-SA/smile-magento-elasticsearch#51]
Hey, with using es 2.2, I get following error on reindex fulltext search in magento:

Can't update non dynamic settings[[index.merge.policy.merge_factor]] for open indices

alias defined in magento admin does not get set (new indice with "datetime" in name is created)

**Comment by afoucret** [comment]
As explain in #50 we won't fix it unti we choose to focus on Magento 2.x version of the extension instead of migration of the Magento 1.x version.

So you should stay on ES 1.7 until we will do the migration.
