### ISSUE TITLE
PHP Fatal error: Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex()

### ISSUE THREAD

**Issue by simbus82** [Smile-SA/smile-magento-elasticsearch#54]
Magento 1.9.2.1
Elastic Search 1.7
Smile Elastic Search  1.3.0

Every time i go to reindex in magento, i receive an Error 500 and in the log i read:

[25-Feb-2016 19:19:46 UTC] PHP Fatal error:  Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in /home/smpnail/public_html/magento/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php on line 181

[25-Feb-2016 19:21:20 UTC] PHP Fatal error:  Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in /home/smpnail/public_html/magento/app/code/community/Smile/ElasticSearch/Model/Indexer/Search/Terms/Position.php on line 121

[25-Feb-2016 19:21:24 UTC] PHP Fatal error:  Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in /home/smpnail/public_html/magento/app/code/community/Smile/VirtualCategories/Model/Indexer/VirtualCategories/Product/Position.php on line 130

**Comment by romainruaud** [comment]
Hello Simone,

this typically occurs when your ElasticSearch instance is not started, then the module fallbacks to the legacy Magento search engine and fails to call the method getCurrentIndex, since it exists only on Smile_ElasticSearch.

Can you please check that your ES instance is properly runnning ?

Regards,

**Comment by simbus82** [comment]
ElasticSearch is working well i think
```
root@master [/]# curl -X GET 'http://localhost:9200'
{
  "status" : 200,
  "name" : "smoker",
  "cluster_name" : "magento",
  "version" : {
    "number" : "1.7.5",
    "build_hash" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "build_timestamp" : "2016-02-02T09:55:30Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

My system is:
- Cloudlinux 6 (CentoOS 6)
- latest WHM/Cpanel (LVM and CageFS enabled)
- apache 2.4
- PHP 5.6
- MariaDB 10

**Comment by afoucret** [comment]
Did you really enable the ES as search engine in the catalog -> search configuration.

Looks like you have still MySQL configured.

**Comment by simbus82** [comment]
I have enabled Smile in Configuration->Catalog->Search, and when i go tu reindex the process go for a long time and then i see 500 for exhausted memory in my system.

If i go to reindex manually the new indices created by Smile, i obtain an Error 500 with errors like:
`[26-Feb-2016 11:46:21 UTC] PHP Fatal error:  Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in /home/smpnail/public_html/magento/app/code/community/Smile/ElasticSearch/Model/Indexer/Search/Terms/Position.php on line 121`

Shop have ~700 products, some product are configurable with ~40 simple product assigned.

Attached you see my setup
![configuration system magento admin](https://cloud.githubusercontent.com/assets/1375730/13351601/21fec76c-dc88-11e5-9693-506fa5c50017.png)
![configuration system magento admin-2](https://cloud.githubusercontent.com/assets/1375730/13351603/2a1a405c-dc88-11e5-8069-0fc6d83fe311.png)

**Comment by romainruaud** [comment]
Maybe something on your customs plugins is interfering with Smile_ElasticSuite. Could you give the module a try on a "clean" Magento install ?

Also, according to http://devdocs.magento.com/guides/m1x/system-requirements.html Magento is not meant to be used with PHP 5.6, and so does our module.

Do you see something in exception.log of Magento ? And did you install all required ES plugins ? If you used the provided installation script (install_es.sh) this should be the case.

Regards,

**Comment by afoucret** [comment]
Hi @simbus82,

Did you finally manage to get everything working ?

**Comment by simbus82** [comment]
YEAH! I have downgraded an account on our Cpanel/CloudLinux and now i can see ES working!
But about php version support of Magento: there are lot of simple solutions to make it working with PHP 7 too.
PHP 5.6 is "supported" de facto, if in official documentation they write 5.5.

Is it hard to let your extension works well with PHP > 5.5?

Downgrading a site (in php 7 or php 5.6) to php 5.5 for us mean losing some performance...

But, thanks for all, you extension is great!!!

**Comment by jdchmiel** [comment]
FYI it seems to work with PHP7, ES 1.7.5, and Magento 1.9.2.4

**Comment by romainruaud** [comment]
I close this one, the initial issue has been fixed.

Thank you @jdchmiel for feedback related to PHP7, it is nice to see that people are experimenting with our module :)

Regards,
