### ISSUE TITLE
It this language/locale related issue?

### ISSUE THREAD

**Issue by doejoe13** [Smile-SA/smile-magento-elasticsearch#59]
Hi, do you support Slovak language, locale sk_SK? Thanks.

{"error":"IndexCreationException[[wellnet-20160314-100307] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to build synonyms]; nested: ParseException[Invalid synonym rule at line 130]; nested: IllegalArgumentException[term: was completely eliminated by analyzer]; ","status":400}
Cannot initialize the indexer process. 

[reindexall.txt](https://github.com/Smile-SA/smile-magento-elasticsearch/files/171709/reindexall.txt)

[wellnet.txt](https://github.com/Smile-SA/smile-magento-elasticsearch/files/171710/wellnet.txt)

**Comment by romainruaud** [comment]
Hello @doejoe13 and apologies for the timelapse.

Did you manage to get it working ? It seems more like an ES-related problem, doesn't it ?

Regards

**Comment by romainruaud** [comment]
Closed due to being too long inactive.

Feel free to reopen this one if you still encounters issues.

Best regards
