### ISSUE TITLE
Undefined indexes 

### ISSUE THREAD

**Issue by WJdeBaas** [Smile-SA/smile-magento-elasticsearch#63]
In class Smile_ElasticSearch_Model_Catalog_Layer_Filter_Attribute

method _getFacetMaxSize
can result in Notice: undefined index "facets_max_size"

method _getFacetSortOrder
can result in Notice: undefined index "facets_sort_order"

Possible solution:
if(isset($attribute['facets_max_size'])){
    return $attribute['facets_max_size'];
}

**Comment by romainruaud** [comment]
Hello. 

This is planned to be fixed on the future release.

Best regards,

**Comment by romainruaud** [comment]
Fixed in 1.4.0
