### ISSUE TITLE
is Smile_Tracker still alive ?

### ISSUE THREAD

**Issue by azurams** [Smile-SA/smile-magento-elasticsearch#67]
Hi,
according to https://github.com/Smile-SA/smile-magento-elasticsearch/issues/30#issuecomment-143672405, shall we understand that ES plugin "tracking-index" is no more available and Tracking functionality is deprecated / abandonned ?

Or where can I find this ES plugin ? 

Thanks

**Comment by romainruaud** [comment]
You are right, this way of tracking is deprecated/abandonned. New version of tracker based on a logstash approach will be published soon in the new version of the module.

Best regards,

**Comment by romainruaud** [comment]
Please see latest 1.4.0 version
