### ISSUE TITLE
Is it possible to obtain a complex search dropdown result block?

### ISSUE THREAD

**Issue by simbus82** [Smile-SA/smile-magento-elasticsearch#70]
I have see this website and it has got a really nice and useful search dropdown (try to write spaghetti or riso for example) http://bit.ly/1O1RUmO

If it is possible, with Elasticsearch and Smile, how to populate "category", "products" and "attribute" for a search keyword? I'm trying to use the "Edit search term" but maybe is not the right place...

Thanks

**Comment by romainruaud** [comment]
Hello Simone, I am afraid that you can not populate results by hand for a given search term. 

However, I do not think that what is appearing on "spaghetti" on this website is something difficult to do with our module. You just need to stylish a bit the autocomplete results block to enlarge it. You already have everything else : "Products", "Categories/Subcategories" (a bit of coding here to have both) and things like "Product Family" or "Region" can be attributes. 

Best regards,

**Comment by simbus82** [comment]
Thanks, for me is a good news. I think i have some problem in a my test project for the issue #71. Maybe attributes too has the same problem...

**Comment by romainruaud** [comment]
I close this one since the question was answered. Feel free to reopen if needed. Best regards.
