### ISSUE TITLE
Is it normal that categories are not indexed?

### ISSUE THREAD

**Issue by simbus82** [Smile-SA/smile-magento-elasticsearch#71]
I have checked all settings, but when i see in some dashboard to see ElasticSearch data (like "head") i see that no categories are indexed. I think this is one of cause that i not see categories in ajax suggest.

Is it normal? 
![elas-cat](https://cloud.githubusercontent.com/assets/1375730/15681336/09d7c3ca-2759-11e6-8377-f81a14b5d455.PNG)

**Comment by romainruaud** [comment]
Hello Simone, it is a known bug of this version, actually fixed in our internal release which should come soon.

Thank you for reporting it.

Best regards,

**Comment by simbus82** [comment]
Thanks @romainruaud, can i apply a patch to solve before the release? Or is needed more work?

**Comment by romainruaud** [comment]
Fixed in 1.4.0
