### ISSUE TITLE
Display Attribute in autocomplete cause error in ajax suggest data

### ISSUE THREAD

**Issue by simbus82** [Smile-SA/smile-magento-elasticsearch#72]
I'm trying to show attribute in autocomplete, so i go inside an attribute (color for example) and i set "yes" on "Display in autocomplete" and "Used in autocomplete".

After if i try the search i don't see suggest, but if i inspect data i see the ajax url for suggest with strange data inside http://www.mysite.it/magento/catalogsearch/ajax/suggest/?q=red

`{"daa699e8fbeeb342d1d249f86af76a6e":{"type":"block","name":"cart_sidebar","arguments":{"template":"checkout\/cart\/sidebar.phtml","type":"checkout\/cart_sidebar"}},"headers":{"type":"headers","name":null,"arguments":null},"3e9f4bf8a0d52dab8e6be7bc1b145d3b":{"type":"block","name":"top.search","arguments":null},"dd4f3f0645cf5f86b4dba8420bad197c":{"type":"block","name":"content","arguments":null},"breadcrumbs":{"type":"breadcrumbs","name":null,"arguments":null},"meta":{"type":"meta","data":{"state":"initializing","extra":null}}}`

If i set to No the "Display in autocomplete" options in my attributes (all attribute must be with "no"), the search suggest works again.

Opening the url http://www.mysite.it/magento/catalogsearch/ajax/suggest/?q=red i see the right html code that generate my suggest block of links.

Am i set something wrong, or is it a bug?

Magento 1.9.2.4

**Comment by romainruaud** [comment]
Hello @simbus82 , any update on this one ?

**Comment by simbus82** [comment]
Sorry @romainruaud, no updates for now, i have to try with new release 1.4
In your test environment do you have this problem?
PS: for install 1.4 i have to overwrite old files or you have some other info to do a good upgrade?

**Comment by romainruaud** [comment]
Hello @simbus82 , I'm afraid that we never faced this issue. The module is running on production in many websites made by Smile and we did not face a such issue.

Please ensure your attribute is set to "used in search" and "used in autocomplete" if you want it to be properly displayed.

Regards,

**Comment by romainruaud** [comment]
Closed due to being too long inactive.

Feel free to reopen this one if you still encounters issues.

Best regards
