### ISSUE TITLE
Some  children categories not showing in layer category block in category view

### ISSUE THREAD

**Issue by nicolasbremard** [Smile-SA/smile-magento-elasticsearch#78]
When viewing category A in frontend, I have an issue in layer block :
- only some of the children categories of cat. A are showing in the layer category block : it seems that only  two or three children categories containing the most part of cat. 1 products.
  The other children categories (which are active and have products) are not showing in the filter.

Is there a way to display all active children categories (with at least one product) in this block ?

Everything is working fine in catalogsearch.
Thanks,

**Comment by romainruaud** [comment]
Hello @nicolasbremard can you give us more details please ? Especially the module's and magento's version.

Also, can you check that the categories are properly set to is_anchor on the Database ?

Best regards,

**Comment by romainruaud** [comment]
I close this one for being too long inactive.

Feel free to reopen if you still encounters an issue.

Regards,

**Comment by scher200** [comment]
@romainruaud I do experience this too. somehow i have a limited categories in my filters bar. Even though I got all my categories set to anchor in the database..
