### ISSUE TITLE
Fatal error on advanced search

### ISSUE THREAD

**Issue by Demoli** [Smile-SA/smile-magento-elasticsearch#8]
Running an advanced search query gives this error

Call to undefined method Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection::addFieldsToFilter() in app\code\core\Mage\CatalogSearch\Model\Advanced.php on line 212

Is advanced search not supported by this module?

Magento CE 1.9.1.0

**Comment by afoucret** [comment]
Not supported yet and not planned (short term at least).
