### ISSUE TITLE
Ubuntu 14.04 / Magento 1.9.2.4 CE / PHP 7 : bad response when reindexing

### ISSUE THREAD

**Issue by rien100moi** [Smile-SA/smile-magento-elasticsearch#80]
Hi,

I've just installed ES and your extension through your script.
I'm working on my local environment.

When I try to reindex : php shell/indexer.php --reindex catalogsearch_fulltext
I'm facing this error : 

Catalog Search Index index process unknown error:
Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 400
[reason phrase] Bad Request
...

I've activated the searchandizing suite in configuration.
I could access http://localhost:9200/_plugin/head/

Am I missing something ?

Thanks in advance !

Vincent.

**Comment by rien100moi** [comment]
I could successfully install ES in a fresh Magento installation.
Maybe it could be data in my current catalog or any extension.

**Comment by romainruaud** [comment]
@rien100moi I close this one then. Feel free to reopen if you are still facing the issue.
