### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mangilaldudi91** [Smile-SA/smile-magento-elasticsearch#82]
When I run the command  ./install-es.sh cluster_name localhost:9200 following issues are generated.

sed: can't read es-conf-templates/elasticsearch.yml: No such file or directory
cp: cannot stat ‘es-conf-templates/logging.yml’: No such file or directory

ERROR: unknown command [-r]. Use [-h] option to list available commands
ERROR: unknown command [-install]. Use [-h] option to list available commands

**Comment by romainruaud** [comment]
Hello @mangilaldudi91 ,

you may miss the proper rights on these files. Are you seeing them on the directory ?

Regards,

**Comment by romainruaud** [comment]
I close this one due to inactivity.

Feel free to reopen if needed @mangilaldudi91 

Regards,
