### ISSUE TITLE
Autocomplete search and result page don't have the same search results

### ISSUE THREAD

**Issue by markus-g** [Smile-SA/smile-magento-elasticsearch#9]
I tested this with a fresh magento 1.9.1 installation with sample data.
catalog and product flat tables are not enabled.

If I enter "wonder" into the search field, it shows "Alice in Wonderland" under products.
Now if I press enter, the result page shows me:
``` 
Search results for 'wonder'

Your search returns no results.  
``` 
I would expect the Alice in Wonderland product here too.

Is this intended?
If so, how can I "fix" this, so that the search results are the same?

**Comment by nicosomb** [comment]
Hello @markus-g!

Yes, it's the intended behavior. When you press Enter, it's not an autocomplete search. Try your example on other website (eg: amazon, ebay, etc.), results in the popin are not the same than results when you press Enter.

Nicolas
